// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as controlwire$0 from "../../../soksak-contract-control/models.js";

/**
 * StreamFrame is one frame on its way to a receiver.
 */
export class StreamFrame {
    /**
     * Stream is the id the caller minted. A receiver reads only its own.
     */
    "stream": string;

    /**
     * Frame is the value. Bytes travel as StreamBytes; anything else is the
     * value itself.
     */
    "frame": any;

    /** Creates a new StreamFrame instance. */
    constructor($$source: Partial<StreamFrame> = {}) {
        if (!("stream" in $$source)) {
            this["stream"] = "";
        }
        if (!("frame" in $$source)) {
            this["frame"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamFrame instance from a string or object.
     */
    static createFrom($$source: any = {}): StreamFrame {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StreamFrame($$parsedSource as Partial<StreamFrame>);
    }
}

/**
 * Served, Unserved and Table are the greeting's, so they are the wire's. What a
 * build answers and what it refuses is read by every client of the plane, and a
 * sidecar answering on its own socket reports the same two lists.
 */
export const Table = controlwire$0.Table;

/**
 * Served, Unserved and Table are the greeting's, so they are the wire's. What a
 * build answers and what it refuses is read by every client of the plane, and a
 * sidecar answering on its own socket reports the same two lists.
 */
export type Table = controlwire$0.Table;
