//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as terminal$0 from "../../../../soksak/soksak-plugin-terminal-xterm/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "terminal:output": $$createType0,
    }));
}

// Private type creation functions
const $$createType0 = terminal$0.Output.createFrom;

configure();
