// Explicit named exports only: the barrel exposes the names Core uses and nothing else.
export {
  ANY_TARGET,
  C2_STATIC_ENFORCEMENT,
  PERMISSIONS,
  PERMISSION_INFO,
  SERVICE_CONTRACT_REQUIREMENT,
  configDefaults,
  configSettingOf,
  contractRequirementSatisfiedBy,
  isArtifactTarget,
  isContentView,
  parseContractProviderRef,
  parseContractRequirement,
  parseManifest,
  parseRegistry,
  parseRegistryPublicKey,
  parseReleaseManifest,
  parseSidecarManifest,
  pluginCommandName,
  programPathSegments,
  qualifiedViewId,
  releaseIdentity,
  resolveText,
  scanHostChromeViolations,
  semverCompare,
  semverGte,
  semverSatisfies,
  serviceOps,
  transparencyViolations,
  unmetNeeds,
  validateSettingValue,
} from "@soksak-ai/plugin-spec";
export type {
  ArtifactTarget,
  CertifiedRegistry,
  ConfigSetting,
  ContractProviderRef,
  ContractRequirement,
  ContributedProgram,
  ContributedSchedule,
  ContributedView,
  EnforcementMode,
  EngineProvision,
  LibraryDep,
  LocalizedText,
  MapEntry,
  PluginManifest,
  PluginPermission,
  PluginRuntimePrincipal,
  ProgramPlatform,
  RegistryCertificationResult,
  RegistryHighWater,
  RegistryPlugin,
  RegistryPublicKey,
  ReleaseArtifact,
  ReleaseDocument,
  ReleaseIdentity,
  ReleaseReference,
  StaticTransparencyRule,
  ViewSurface,
} from "@soksak-ai/plugin-spec";
export { BANNED_DOM_MORPHEMES } from "./identityVocabulary";
