// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CaptureService exposes window capture to anything driving this application.
 * 
 * A capability with no command cannot be verified from outside, and "there was
 * no command for it" is not a reason to leave something unobserved.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Pixels answers with a base64 PNG instead of touching the disk, for callers
 * that only want to look.
 */
export function Pixels(rect: $models.Rect): $CancellablePromise<string> {
    return $Call.ByID(970833820, rect);
}

/**
 * Snapshot writes a PNG of the whole window and answers with where it landed.
 * 
 * The path is returned rather than assumed, so a caller verifies from the
 * response instead of guessing where the file went.
 */
export function Snapshot(path: string): $CancellablePromise<$models.CaptureNote> {
    return $Call.ByID(3039522845, path).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SnapshotRegion writes a PNG cropped to a window-relative rect in CSS points.
 */
export function SnapshotRegion(path: string, rect: $models.Rect): $CancellablePromise<$models.CaptureNote> {
    return $Call.ByID(3826199269, path, rect).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.CaptureNote.createFrom;
