// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ControlService is the frontend's door to the command registry.
 * 
 * It is a transport, not a second registry: every name resolves through the
 * same table a socket or an agent would reach, so no caller can take a path
 * that answers differently.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../../encoding/json/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as control$0 from "../../core/control/models.js";

/**
 * Commands answers with what this build serves and what it refuses, so a
 * caller can tell "not written yet" from "impossible here" without guessing.
 */
export function Commands(): $CancellablePromise<control$0.Table> {
    return $Call.ByID(2697978628).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Invoke runs one command. Arguments arrive as a JSON object because the
 * registry is typed per command rather than at this boundary.
 */
export function Invoke(name: string, args: { [_ in string]?: json$0.RawMessage }): $CancellablePromise<any> {
    return $Call.ByID(806562942, name, args);
}

// Private type creation functions
const $$createType0 = control$0.Table.createFrom;
