// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CaptureNote is what a capture contains, beside the image.
 * 
 * The path is answered rather than assumed, so a caller reads where the file
 * landed instead of guessing it went where it asked.
 */
export class CaptureNote {
    "path": string;

    /**
     * DocumentOnly states that the native children are not in this image: the window capture
     * was refused and the web view was asked for the document instead. A picture that leaves
     * something out and does not say so is read as a window that had nothing there.
     */
    "documentOnly"?: boolean;

    /** Creates a new CaptureNote instance. */
    constructor($$source: Partial<CaptureNote> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CaptureNote instance from a string or object.
     */
    static createFrom($$source: any = {}): CaptureNote {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CaptureNote($$parsedSource as Partial<CaptureNote>);
    }
}

/**
 * CapturePixels is an image and the statement of what went into it.
 * 
 * The two travel together. This is the capture with no file left behind to
 * inspect afterwards, so a caller that receives only the image has no way to
 * ask later what was drawn — and it threw the note away entirely, which made
 * the one path an agent looks through the one path with no evidence.
 */
export class CapturePixels {
    "png": string;
    "note": CaptureNote;

    /** Creates a new CapturePixels instance. */
    constructor($$source: Partial<CapturePixels> = {}) {
        if (!("png" in $$source)) {
            this["png"] = "";
        }
        if (!("note" in $$source)) {
            this["note"] = (new CaptureNote());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CapturePixels instance from a string or object.
     */
    static createFrom($$source: any = {}): CapturePixels {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("note" in $$parsedSource) {
            $$parsedSource["note"] = $$createField1_0($$parsedSource["note"]);
        }
        return new CapturePixels($$parsedSource as Partial<CapturePixels>);
    }
}

/**
 * RecordReport is what a burst left behind.
 * 
 * Frames is what landed on disk, which is not always what was asked for, and
 * Stopped is why when they differ. A count with no reason next to it makes a
 * short recording and a complete one the same answer.
 */
export class RecordReport {
    "dir": string;
    "requested": number;
    "frames": number;
    "bytes": number;
    "stopped"?: string;

    /** Creates a new RecordReport instance. */
    constructor($$source: Partial<RecordReport> = {}) {
        if (!("dir" in $$source)) {
            this["dir"] = "";
        }
        if (!("requested" in $$source)) {
            this["requested"] = 0;
        }
        if (!("frames" in $$source)) {
            this["frames"] = 0;
        }
        if (!("bytes" in $$source)) {
            this["bytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecordReport instance from a string or object.
     */
    static createFrom($$source: any = {}): RecordReport {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecordReport($$parsedSource as Partial<RecordReport>);
    }
}

/**
 * RecordRequest is one burst.
 */
export class RecordRequest {
    /**
     * Dir holds the frames. It is created if it is not there.
     */
    "Dir": string;

    /**
     * Frames is how many to take, 1 through recordMaxFrames.
     */
    "Frames": number;

    /**
     * IntervalMs is the wait between them, 0 through recordMaxIntervalMs. Zero
     * is as fast as the capture answers, which is a legitimate request.
     */
    "IntervalMs": number;

    /**
     * MaxBytes is a cumulative ceiling on encoded frame bytes, 0 for none. The
     * frame that would cross it is not written, and the ones before it stay.
     */
    "MaxBytes": number;

    /**
     * Region is the part of the window each frame holds. The zero value is the
     * whole window.
     */
    "Region": Rect;

    /**
     * FrameTimeoutMs bounds one frame's grab, 1 through recordMaxFrameTimeoutMs.
     * Zero takes the default.
     * 
     * A grab that never comes back would hold the whole burst, and a recording
     * that stops at frame 3 of 600 with no reason is indistinguishable from one
     * nobody started. After the deadline the receiver is detached, so a late
     * frame cannot write a file out of order.
     */
    "FrameTimeoutMs": number;

    /** Creates a new RecordRequest instance. */
    constructor($$source: Partial<RecordRequest> = {}) {
        if (!("Dir" in $$source)) {
            this["Dir"] = "";
        }
        if (!("Frames" in $$source)) {
            this["Frames"] = 0;
        }
        if (!("IntervalMs" in $$source)) {
            this["IntervalMs"] = 0;
        }
        if (!("MaxBytes" in $$source)) {
            this["MaxBytes"] = 0;
        }
        if (!("Region" in $$source)) {
            this["Region"] = (new Rect());
        }
        if (!("FrameTimeoutMs" in $$source)) {
            this["FrameTimeoutMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecordRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): RecordRequest {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Region" in $$parsedSource) {
            $$parsedSource["Region"] = $$createField4_0($$parsedSource["Region"]);
        }
        return new RecordRequest($$parsedSource as Partial<RecordRequest>);
    }
}

/**
 * Rect is a window-relative region in CSS points with a top-left origin, the
 * same coordinate contract the DOM and the compositor already share. A zero
 * rect means the whole window.
 */
export class Rect {
    "x": number;
    "y": number;
    "width": number;
    "height": number;

    /** Creates a new Rect instance. */
    constructor($$source: Partial<Rect> = {}) {
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Rect instance from a string or object.
     */
    static createFrom($$source: any = {}): Rect {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Rect($$parsedSource as Partial<Rect>);
    }
}

/**
 * Reply is one command's answer, encoded.
 * 
 * A string rather than a value because a bare `any` does not survive this
 * transport intact. Measured 2026-08-15: data_kv_get for a key that does not
 * exist answered null over the socket and {} here, and the frontend took the {}
 * for the stored value — three boots died on `slots.filter`, `workspaces.length`
 * and `t.map`, all of them that one difference.
 * 
 * One registry, several transports is only true if the transports agree about
 * what a command said. This is where that is made true rather than hoped for.
 */
export class Reply {
    "result": string;

    /** Creates a new Reply instance. */
    constructor($$source: Partial<Reply> = {}) {
        if (!("result" in $$source)) {
            this["result"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Reply instance from a string or object.
     */
    static createFrom($$source: any = {}): Reply {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Reply($$parsedSource as Partial<Reply>);
    }
}

// Private type creation functions
const $$createType0 = CaptureNote.createFrom;
const $$createType1 = Rect.createFrom;
