// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CaptureNote is what a capture contains, beside the file.
 * 
 * A capture that quietly left a pane empty is the defect this whole path exists to remove, so the
 * answer states how many surfaces it drew and why any were left out. Without it a caller looking
 * at a flat rectangle cannot tell a page that failed to load from a composite that never ran.
 */
export class CaptureNote {
    "path": string;

    /**
     * Surfaces is how many native surfaces the inventory held at capture time.
     */
    "surfaces": number;

    /**
     * Drawn is how many of them were drawn into the image.
     */
    "drawn": number;

    /**
     * Skipped names each one that was not, with the reason.
     */
    "skipped"?: string[];

    /** Creates a new CaptureNote instance. */
    constructor($$source: Partial<CaptureNote> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("surfaces" in $$source)) {
            this["surfaces"] = 0;
        }
        if (!("drawn" in $$source)) {
            this["drawn"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CaptureNote instance from a string or object.
     */
    static createFrom($$source: any = {}): CaptureNote {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("skipped" in $$parsedSource) {
            $$parsedSource["skipped"] = $$createField3_0($$parsedSource["skipped"]);
        }
        return new CaptureNote($$parsedSource as Partial<CaptureNote>);
    }
}

/**
 * Rect is a window-relative region in CSS points with a top-left origin, the
 * same coordinate contract the DOM and the compositor already share. A zero
 * rect means the whole window.
 */
export class Rect {
    "x": number;
    "y": number;
    "width": number;
    "height": number;

    /** Creates a new Rect instance. */
    constructor($$source: Partial<Rect> = {}) {
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Rect instance from a string or object.
     */
    static createFrom($$source: any = {}): Rect {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Rect($$parsedSource as Partial<Rect>);
    }
}

/**
 * Reply is one command's answer, encoded.
 * 
 * A string rather than a value because a bare `any` does not survive this
 * transport intact. Measured 2026-08-15: data_kv_get for a key that does not
 * exist answered null over the socket and {} here, and the frontend took the {}
 * for the stored value — three boots died on `slots.filter`, `workspaces.length`
 * and `t.map`, all of them that one difference.
 * 
 * One registry, several transports is only true if the transports agree about
 * what a command said. This is where that is made true rather than hoped for.
 */
export class Reply {
    "result": string;

    /** Creates a new Reply instance. */
    constructor($$source: Partial<Reply> = {}) {
        if (!("result" in $$source)) {
            this["result"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Reply instance from a string or object.
     */
    static createFrom($$source: any = {}): Reply {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Reply($$parsedSource as Partial<Reply>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
