// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Rect is a window-relative region in CSS points with a top-left origin, the
 * same coordinate contract the DOM and the compositor already share. A zero
 * rect means the whole window.
 */
export class Rect {
    "x": number;
    "y": number;
    "width": number;
    "height": number;

    /** Creates a new Rect instance. */
    constructor($$source: Partial<Rect> = {}) {
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Rect instance from a string or object.
     */
    static createFrom($$source: any = {}): Rect {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Rect($$parsedSource as Partial<Rect>);
    }
}
