// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as nativesurface$0 from "../wails-service-native-compositor/models.js";

export class SurfaceStatus {
    /**
     * Creates a new SurfaceStatus instance.
     * @param {Partial<SurfaceStatus>} [$$source = {}] - The source object to create the SurfaceStatus.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("generation" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["generation"] = 0;
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("frame" in $$source)) {
            /**
             * @member
             * @type {nativesurface$0.Frame}
             */
            this["frame"] = (new nativesurface$0.Frame());
        }
        if (!("visible" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["visible"] = false;
        }
        if (!("alpha" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["alpha"] = 0;
        }
        if (!("layer" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["layer"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SurfaceStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SurfaceStatus}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("frame" in $$parsedSource) {
            $$parsedSource["frame"] = $$createField3_0($$parsedSource["frame"]);
        }
        return new SurfaceStatus(/** @type {Partial<SurfaceStatus>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = nativesurface$0.Frame.createFrom;
