// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as nativesurface$0 from "../wails-service-native-compositor/models.js";

export class SurfaceStatus {
    "id": string;
    "generation": number;
    "url": string;
    "frame": nativesurface$0.Frame;
    "visible": boolean;
    "alpha": number;
    "layer": number;

    /** Creates a new SurfaceStatus instance. */
    constructor($$source: Partial<SurfaceStatus> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("generation" in $$source)) {
            this["generation"] = 0;
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("frame" in $$source)) {
            this["frame"] = (new nativesurface$0.Frame());
        }
        if (!("visible" in $$source)) {
            this["visible"] = false;
        }
        if (!("alpha" in $$source)) {
            this["alpha"] = 0;
        }
        if (!("layer" in $$source)) {
            this["layer"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SurfaceStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): SurfaceStatus {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("frame" in $$parsedSource) {
            $$parsedSource["frame"] = $$createField3_0($$parsedSource["frame"]);
        }
        return new SurfaceStatus($$parsedSource as Partial<SurfaceStatus>);
    }
}

// Private type creation functions
const $$createType0 = nativesurface$0.Frame.createFrom;
