// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} id
 * @param {number} generation
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function Navigate(id, generation, url) {
    return $Call.ByID(1630749398, id, generation, url);
}

/**
 * @returns {$CancellablePromise<$models.SurfaceStatus[]>}
 */
export function Status() {
    return $Call.ByID(1340209055).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.SurfaceStatus.createFrom;
const $$createType1 = $Create.Array($$createType0);
