// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Handle {
    /**
     * Creates a new Handle instance.
     * @param {Partial<Handle>} [$$source = {}] - The source object to create the Handle.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("generation" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["generation"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Handle instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Handle}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Handle(/** @type {Partial<Handle>} */($$parsedSource));
    }
}

export class InputTrace {
    /**
     * Creates a new InputTrace instance.
     * @param {Partial<InputTrace>} [$$source = {}] - The source object to create the InputTrace.
     */
    constructor($$source = {}) {
        if (!("sequence" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sequence"] = 0;
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["data"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["inputType"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | null | undefined}
             */
            this["isComposing"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["key"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["keyCode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["message"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InputTrace instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InputTrace}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InputTrace(/** @type {Partial<InputTrace>} */($$parsedSource));
    }
}

export class Output {
    /**
     * Creates a new Output instance.
     * @param {Partial<Output>} [$$source = {}] - The source object to create the Output.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("generation" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["generation"] = 0;
        }
        if (!("dataBase64" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dataBase64"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Output instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Output}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Output(/** @type {Partial<Output>} */($$parsedSource));
    }
}

export class Status {
    /**
     * Creates a new Status instance.
     * @param {Partial<Status>} [$$source = {}] - The source object to create the Status.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("generation" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["generation"] = 0;
        }
        if (!("pid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pid"] = 0;
        }
        if (!("inputTrace" in $$source)) {
            /**
             * @member
             * @type {InputTrace[]}
             */
            this["inputTrace"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Status}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("inputTrace" in $$parsedSource) {
            $$parsedSource["inputTrace"] = $$createField3_0($$parsedSource["inputTrace"]);
        }
        return new Status(/** @type {Partial<Status>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = InputTrace.createFrom;
const $$createType1 = $Create.Array($$createType0);
