// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Handle {
    "id": string;
    "generation": number;

    /** Creates a new Handle instance. */
    constructor($$source: Partial<Handle> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("generation" in $$source)) {
            this["generation"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Handle instance from a string or object.
     */
    static createFrom($$source: any = {}): Handle {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Handle($$parsedSource as Partial<Handle>);
    }
}

export class InputTrace {
    "sequence": number;
    "kind": string;
    "data"?: string | null;
    "inputType"?: string;
    "isComposing"?: boolean | null;
    "key"?: string;
    "keyCode"?: number;
    "message"?: string;

    /** Creates a new InputTrace instance. */
    constructor($$source: Partial<InputTrace> = {}) {
        if (!("sequence" in $$source)) {
            this["sequence"] = 0;
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InputTrace instance from a string or object.
     */
    static createFrom($$source: any = {}): InputTrace {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InputTrace($$parsedSource as Partial<InputTrace>);
    }
}

export class Output {
    "id": string;
    "generation": number;
    "dataBase64": string;

    /** Creates a new Output instance. */
    constructor($$source: Partial<Output> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("generation" in $$source)) {
            this["generation"] = 0;
        }
        if (!("dataBase64" in $$source)) {
            this["dataBase64"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Output instance from a string or object.
     */
    static createFrom($$source: any = {}): Output {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Output($$parsedSource as Partial<Output>);
    }
}

export class Status {
    "id": string;
    "generation": number;
    "pid": number;
    "inputTrace": InputTrace[];

    /** Creates a new Status instance. */
    constructor($$source: Partial<Status> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("generation" in $$source)) {
            this["generation"] = 0;
        }
        if (!("pid" in $$source)) {
            this["pid"] = 0;
        }
        if (!("inputTrace" in $$source)) {
            this["inputTrace"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     */
    static createFrom($$source: any = {}): Status {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("inputTrace" in $$parsedSource) {
            $$parsedSource["inputTrace"] = $$createField3_0($$parsedSource["inputTrace"]);
        }
        return new Status($$parsedSource as Partial<Status>);
    }
}

// Private type creation functions
const $$createType0 = InputTrace.createFrom;
const $$createType1 = $Create.Array($$createType0);
