// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Close(handle: $models.Handle): $CancellablePromise<void> {
    return $Call.ByID(170368024, handle);
}

/**
 * Open starts a shell for id and sends its bytes to stream.
 * 
 * An empty stream opens a shell nobody reads. The caller asked for a process,
 * not for its output, and that is what a round-trip check over the control
 * plane does.
 */
export function Open(id: string, stream: string, cols: number, rows: number): $CancellablePromise<$models.Handle> {
    return $Call.ByID(2123408004, id, stream, cols, rows).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Reap closes every session this service holds and answers how many it closed.
 * 
 * The count is this service's own — nothing else knows how many sessions it
 * held — and it is what `app_shutdown_prepare` puts in the receipt a caller
 * checks before the process goes away. A shutdown that reaped correctly and
 * reported nothing could not be part of that receipt, so the one command that
 * quits the application was declared unserved (measured 2026-08-16: `sok
 * app.shutdown.commit` answered INTERNAL).
 * 
 * Idempotent, and a second call answers zero rather than the first count: a
 * number that repeated itself would report work that did not happen.
 */
export function Reap(): $CancellablePromise<number> {
    return $Call.ByID(3248855604);
}

export function Resize(handle: $models.Handle, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(2168070844, handle, cols, rows);
}

export function Status(): $CancellablePromise<$models.Status[]> {
    return $Call.ByID(2704316750).then(($result: any) => {
        return $$createType2($result);
    });
}

export function TraceInput(handle: $models.Handle, event: $models.InputTrace): $CancellablePromise<void> {
    return $Call.ByID(193933387, handle, event);
}

export function Write(handle: $models.Handle, data: string): $CancellablePromise<void> {
    return $Call.ByID(3966941107, handle, data);
}

// Private type creation functions
const $$createType0 = $models.Handle.createFrom;
const $$createType1 = $models.Status.createFrom;
const $$createType2 = $Create.Array($$createType1);
