// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {$models.Handle} handle
 * @returns {$CancellablePromise<void>}
 */
export function Close(handle) {
    return $Call.ByID(170368024, handle);
}

/**
 * @param {string} id
 * @param {number} cols
 * @param {number} rows
 * @returns {$CancellablePromise<$models.Handle>}
 */
export function Open(id, cols, rows) {
    return $Call.ByID(2123408004, id, cols, rows).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.Handle} handle
 * @param {number} cols
 * @param {number} rows
 * @returns {$CancellablePromise<void>}
 */
export function Resize(handle, cols, rows) {
    return $Call.ByID(2168070844, handle, cols, rows);
}

/**
 * @returns {$CancellablePromise<$models.Status[]>}
 */
export function Status() {
    return $Call.ByID(2704316750).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {$models.Handle} handle
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function Write(handle, data) {
    return $Call.ByID(3966941107, handle, data);
}

// Private type creation functions
const $$createType0 = $models.Handle.createFrom;
const $$createType1 = $models.Status.createFrom;
const $$createType2 = $Create.Array($$createType1);
