// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Close(handle: $models.Handle): $CancellablePromise<void> {
    return $Call.ByID(170368024, handle);
}

export function Open(id: string, cols: number, rows: number): $CancellablePromise<$models.Handle> {
    return $Call.ByID(2123408004, id, cols, rows).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Resize(handle: $models.Handle, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(2168070844, handle, cols, rows);
}

export function Status(): $CancellablePromise<$models.Status[]> {
    return $Call.ByID(2704316750).then(($result: any) => {
        return $$createType2($result);
    });
}

export function TraceInput(handle: $models.Handle, event: $models.InputTrace): $CancellablePromise<void> {
    return $Call.ByID(193933387, handle, event);
}

export function Write(handle: $models.Handle, data: string): $CancellablePromise<void> {
    return $Call.ByID(3966941107, handle, data);
}

// Private type creation functions
const $$createType0 = $models.Handle.createFrom;
const $$createType1 = $models.Status.createFrom;
const $$createType2 = $Create.Array($$createType1);
