// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ControlService is the frontend's door to the command registry.
 * 
 * It is a transport, not a second registry: every name resolves through the
 * same table a socket or an agent would reach, so no caller can take a path
 * that answers differently.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as controlwire$0 from "../../../soksak-contract-control/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as control$0 from "../../core/control/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Commands answers with what this build serves and what it refuses, so a
 * caller can tell "not written yet" from "impossible here" without guessing.
 */
export function Commands(): $CancellablePromise<control$0.Table> {
    return $Call.ByID(1177719295).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Invoke runs one command.
 * 
 * Arguments arrive as ordinary values and are re-encoded here, once. The
 * registry is typed per command rather than at this boundary, so each handler
 * decodes what it needs; encoding on the frontend side instead would double-
 * encode every string (measured 2026-08-15: "core" arrived as "\"core\"").
 * The context includes the window that made the call. Taking it is what lets the
 * registry stamp the caller: a window cannot name itself, because a window that
 * could name itself could name another one, and then a command's effect depends
 * on what the renderer claimed rather than on where it ran.
 */
export function Invoke(name: string, args: { [_ in string]?: any }): $CancellablePromise<$models.Reply> {
    return $Call.ByID(1218673521, name, args).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = controlwire$0.Table.createFrom;
const $$createType1 = $models.Reply.createFrom;
