// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as CaptureService from "./captureservice.js";
import * as ControlService from "./controlservice.js";
export {
    CaptureService,
    ControlService
};

export {
    BurstReport,
    BurstRequest,
    CaptureNote,
    CapturePixels,
    RecordReport,
    RecordRequest,
    Rect,
    Reply,
    WindowGone
} from "./models.js";
