// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * nativePresentationService keeps the provider inventory service name and API,
 * but closes one missing ordering edge: after every native provider has applied
 * its children, Core's pointer-transparent decoration plane is raised last.
 * Embedding preserves every compositor method and its existing binding surface.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as nativesurface$0 from "../../../../min-median-max/wails-service-native-compositor/models.js";

export function Commit(snapshot: nativesurface$0.Snapshot): $CancellablePromise<nativesurface$0.Receipt> {
    return $Call.ByID(273482336, snapshot).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Explicit delegates keep the generated TypeScript surface auditable against this Go type. Promoted
 * methods are callable at runtime, but the repository gate deliberately does not infer an embedded
 * dependency's API as this service's declared API.
 */
export function CoverIn(window: string): $CancellablePromise<{ [_ in string]?: nativesurface$0.Cover }> {
    return $Call.ByID(2263669131, window).then(($result: any) => {
        return $$createType2($result);
    });
}

export function Deliver(id: string, message: { [_ in string]?: any }): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(1961491570, id, message).then(($result: any) => {
        return $$createType3($result);
    });
}

export function Drain(): $CancellablePromise<[number, number]> {
    return $Call.ByID(317344533);
}

export function History(window: string, sinceUnixMs: number): $CancellablePromise<nativesurface$0.Composition[]> {
    return $Call.ByID(4008767403, window, sinceUnixMs).then(($result: any) => {
        return $$createType5($result);
    });
}

export function Kinds(): $CancellablePromise<nativesurface$0.SurfaceKind[]> {
    return $Call.ByID(2725844316).then(($result: any) => {
        return $$createType6($result);
    });
}

export function Latest(window: string): $CancellablePromise<nativesurface$0.Composition> {
    return $Call.ByID(1983586762, window).then(($result: any) => {
        return $$createType4($result);
    });
}

export function Status(window: string): $CancellablePromise<nativesurface$0.Receipt> {
    return $Call.ByID(197140955, window).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SurfaceAt(window: string, x: number, y: number): $CancellablePromise<string> {
    return $Call.ByID(3442354533, window, x, y);
}

export function Windows(): $CancellablePromise<string[]> {
    return $Call.ByID(564122126).then(($result: any) => {
        return $$createType7($result);
    });
}

// Private type creation functions
const $$createType0 = nativesurface$0.Receipt.createFrom;
const $$createType1 = nativesurface$0.Cover.createFrom;
const $$createType2 = $Create.Map($Create.Any, $$createType1);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = nativesurface$0.Composition.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Array($Create.Any);
const $$createType7 = $Create.Array($Create.Any);
