// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as TerminalService from "./terminalservice.js";
export {
    TerminalService
};

export {
    TerminalHandle,
    TerminalOutput
} from "./models.js";
