// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class TerminalHandle {
    /**
     * Creates a new TerminalHandle instance.
     * @param {Partial<TerminalHandle>} [$$source = {}] - The source object to create the TerminalHandle.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("generation" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["generation"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalHandle instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TerminalHandle}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TerminalHandle(/** @type {Partial<TerminalHandle>} */($$parsedSource));
    }
}

export class TerminalOutput {
    /**
     * Creates a new TerminalOutput instance.
     * @param {Partial<TerminalOutput>} [$$source = {}] - The source object to create the TerminalOutput.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("generation" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["generation"] = 0;
        }
        if (!("data" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["data"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalOutput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TerminalOutput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TerminalOutput(/** @type {Partial<TerminalOutput>} */($$parsedSource));
    }
}
