// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} id
 * @param {number} generation
 * @returns {$CancellablePromise<void>}
 */
export function Close(id, generation) {
    return $Call.ByID(3052890075, id, generation);
}

/**
 * @param {string} id
 * @param {number} cols
 * @param {number} rows
 * @returns {$CancellablePromise<$models.TerminalHandle>}
 */
export function Open(id, cols, rows) {
    return $Call.ByID(145539729, id, cols, rows).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @param {number} generation
 * @param {number} cols
 * @param {number} rows
 * @returns {$CancellablePromise<void>}
 */
export function Resize(id, generation, cols, rows) {
    return $Call.ByID(270758441, id, generation, cols, rows);
}

/**
 * @param {string} id
 * @param {number} generation
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function Write(id, generation, data) {
    return $Call.ByID(371925220, id, generation, data);
}

// Private type creation functions
const $$createType0 = $models.TerminalHandle.createFrom;
