import { ANY_TARGET, parseManifest, parseSidecarManifest, releaseIdentity, type ArtifactTarget, type CertifiedRegistryIndex, type ReleaseArtifact, type ReleaseDocument, type ReleaseIdentity } from "./spec";
export interface RegistryDocumentLoader { load(url: string): Promise<Uint8Array> }
export interface RegistryInstallTransaction { transactionId: string }
export interface StagedRegistryArtifact { handle: string; sha256: string; size: number; manifestSha256: string; extraction: "regular-files-only"; verifiedEntrypoints?: readonly string[] }
export interface VerifiedInstallRelease extends ReleaseIdentity { registryId: string; sourceRepository: string; sourceCommit: string; artifactUrl: string; artifactSha256: string; target: ArtifactTarget; manifestSha256: string; stagedHandle: string }
export interface RegistryArtifactStager { begin(input:{registryId:string;root:ReleaseIdentity}):Promise<RegistryInstallTransaction>; stage(input:{transactionId:string;registryId:string;release:ReleaseIdentity;artifact:ReleaseArtifact}):Promise<StagedRegistryArtifact>; readUtf8(transactionId:string,handle:string,path:string):Promise<string>; commit(transactionId:string,releases:readonly VerifiedInstallRelease[]):Promise<{revision:number}>; rollback(transactionId:string):Promise<void> }
export type RegistryInstallFailureCode="ROOT_NOT_FOUND"|"RELEASE_VERIFICATION_FAILED"|"TARGET_NOT_AVAILABLE"|"UNSAFE_EXTRACTION"|"ATOMIC_INSTALL_FAILED";
export type RegistryInstallResult={ok:true;registryId:string;revision:number;releases:VerifiedInstallRelease[]}|{ok:false;code:RegistryInstallFailureCode;errors:string[]};
export interface RegistryInstallRequest {certified:CertifiedRegistryIndex;root:ReleaseIdentity;target:ArtifactTarget;documents:RegistryDocumentLoader;artifacts:RegistryArtifactStager}
class InstallFailure extends Error{constructor(readonly code:RegistryInstallFailureCode,readonly errors:string[]){super(errors.join("; "));}}
function releases(index:CertifiedRegistryIndex["index"]):ReleaseDocument[]{return [...index.plugins,...index.sidecars,...index.kits,...index.contracts,...index.specs];}
function releaseOf(certified:CertifiedRegistryIndex,wanted:ReleaseIdentity):ReleaseDocument|null{return releases(certified.index).find((release)=>{const value=releaseIdentity(release);return value.kind===wanted.kind&&value.id===wanted.id&&value.version===wanted.version;})??null;}
function artifactOf(release:ReleaseDocument,target:ArtifactTarget):ReleaseArtifact{const artifact=release.artifacts.find((value)=>value.target===target)??release.artifacts.find((value)=>value.target===ANY_TARGET);if(!artifact)throw new InstallFailure("TARGET_NOT_AVAILABLE",["release has no artifact for "+target]);return artifact;}
export function declaredEntrypoints(artifact:ReleaseArtifact):string[]{return[artifact.manifest];}
function stageEvidence(staged:StagedRegistryArtifact,artifact:ReleaseArtifact):void{const errors:string[]=[];if(staged.extraction!=="regular-files-only")errors.push("native extraction policy missing");if(staged.sha256!==artifact.sha256)errors.push("artifact digest mismatch");if(staged.size!==artifact.size)errors.push("artifact size mismatch");if(!/^[a-f0-9]{64}$/.test(staged.manifestSha256))errors.push("manifest digest missing");if(!staged.verifiedEntrypoints?.includes(artifact.manifest))errors.push("manifest entrypoint not verified");if(errors.length)throw new InstallFailure("UNSAFE_EXTRACTION",errors);}
async function validateStaged(stager:RegistryArtifactStager,transactionId:string,staged:StagedRegistryArtifact,release:ReleaseDocument,artifact:ReleaseArtifact):Promise<void>{const raw=JSON.parse(await stager.readUtf8(transactionId,staged.handle,artifact.manifest));if("plugin"in release){const parsed=parseManifest(raw,release.plugin.id);if(!parsed.validation.ok||parsed.manifest?.version!==release.plugin.version)throw new InstallFailure("RELEASE_VERIFICATION_FAILED",parsed.validation.errors);}else if("sidecar"in release){const parsed=parseSidecarManifest(raw);if(!parsed.ok||parsed.value.id!==release.sidecar.id||parsed.value.version!==release.sidecar.version)throw new InstallFailure("RELEASE_VERIFICATION_FAILED",parsed.ok?["sidecar identity mismatch"]:parsed.errors);}}
export async function installRegistryRelease(request:RegistryInstallRequest):Promise<RegistryInstallResult>{let transactionId:string|null=null;try{const release=releaseOf(request.certified,request.root);if(!release)throw new InstallFailure("ROOT_NOT_FOUND",["release absent from certified registry"]);const artifact=artifactOf(release,request.target);const transaction=await request.artifacts.begin({registryId:request.certified.index.id,root:request.root});transactionId=transaction.transactionId;const staged=await request.artifacts.stage({transactionId,registryId:request.certified.index.id,release:request.root,artifact});stageEvidence(staged,artifact);await validateStaged(request.artifacts,transactionId,staged,release,artifact);const verified=Object.freeze({...request.root,registryId:request.certified.index.id,sourceRepository:release.source.repository,sourceCommit:release.source.commit,artifactUrl:artifact.url,artifactSha256:artifact.sha256,target:artifact.target,manifestSha256:staged.manifestSha256,stagedHandle:staged.handle});const committed=await request.artifacts.commit(transactionId,[verified]);transactionId=null;return{ok:true,registryId:request.certified.index.id,revision:committed.revision,releases:[verified]};}catch(cause){if(transactionId!==null)await request.artifacts.rollback(transactionId).catch(()=>{});if(cause instanceof InstallFailure)return{ok:false,code:cause.code,errors:cause.errors};return{ok:false,code:"ATOMIC_INSTALL_FAILED",errors:[String(cause)]};}}
