import { parseRegistryPublicKey, semverCompare, type CertifiedRegistry, type LocalizedText, type ReleaseReference, type RegistryPublicKey } from "./spec";
export const OFFICIAL_REGISTRY_ID = "official";
export interface RegistryDescriptor { id: string; name: string; indexUrl: string; visibility: "public" | "private"; trustedPublicKey: RegistryPublicKey; credentialRef?: string }
export interface RegistryCredentialSlot { namespace: string; key: "http-authorization"; ref: string }
// An index entry pins one plugin release by {id, version, size, sha256}; the location is derived.
export interface QualifiedRegistryEntry extends ReleaseReference { registryId: string }
export type RegistryEntry = QualifiedRegistryEntry;
const REGISTRY_ID_RE = /^[a-z0-9][a-z0-9._-]{0,63}$/;
const isRecord = (value: unknown): value is Record<string, unknown> => typeof value === "object" && value !== null && !Array.isArray(value);
const hasOnlyKeys = (value: Record<string, unknown>, allowed: readonly string[]): boolean => Object.keys(value).every((key) => allowed.includes(key));
export function registryCredentialSlot(registryId: string): RegistryCredentialSlot | null { if (!REGISTRY_ID_RE.test(registryId)) return null; const encoded = [...registryId].map((c) => c === "-" ? "--" : c === "." ? "-d" : c === "_" ? "-u" : c).join(""); const namespace = "core_registry-" + encoded; return { namespace, key: "http-authorization", ref: namespace + "/http-authorization" }; }
export function isRegistryIndexUrl(value: unknown): value is string { if (typeof value !== "string" || value !== value.trim() || /[\u0000-\u001f\u007f\\?#]/.test(value)) return false; try { const url = new URL(value); return url.protocol === "https:" && url.username === "" && url.password === "" && url.search === "" && url.hash === "" && url.toString() === value; } catch { return false; } }
export function parseRegistryDescriptor(raw: unknown): RegistryDescriptor | null { if (!isRecord(raw) || !hasOnlyKeys(raw, ["credentialRef", "id", "indexUrl", "name", "trustedPublicKey", "visibility"]) || typeof raw.id !== "string" || !REGISTRY_ID_RE.test(raw.id) || typeof raw.name !== "string" || !raw.name.trim() || !isRegistryIndexUrl(raw.indexUrl) || (raw.visibility !== "public" && raw.visibility !== "private")) return null; const key = parseRegistryPublicKey(raw.trustedPublicKey); if (!key.ok) return null; if (raw.visibility === "public") return raw.credentialRef === undefined ? { id: raw.id, name: raw.name, indexUrl: raw.indexUrl, visibility: "public", trustedPublicKey: key.value } : null; const slot = registryCredentialSlot(raw.id); if (!slot || (raw.credentialRef !== undefined && raw.credentialRef !== slot.ref)) return null; return { id: raw.id, name: raw.name, indexUrl: raw.indexUrl, visibility: "private", trustedPublicKey: key.value, credentialRef: slot.ref }; }
export function qualifyRegistry(certified: CertifiedRegistry): QualifiedRegistryEntry[] { return certified.registry.plugins.map((plugin) => ({ registryId: certified.registry.id, ...plugin })); }
export type RegistryReleaseResolution = { ok: true; entry: QualifiedRegistryEntry } | { ok: false; reason: "not_found" | "qualification_required" | "ambiguous"; candidates: { registryId: string; id: string; version: string }[] };
export function resolveRegistryRelease(entries: readonly QualifiedRegistryEntry[], target: { registryId?: string; id: string }): RegistryReleaseResolution { const matches = entries.filter((entry) => entry.id === target.id && (target.registryId === undefined || entry.registryId === target.registryId)); const candidates = matches.map(({registryId,id,version})=>({registryId,id,version})).sort((a,b)=>a.registryId.localeCompare(b.registryId) || -(semverCompare(a.version,b.version) ?? 0)); if (!matches.length) return {ok:false,reason:"not_found",candidates}; if (new Set(matches.map((entry)=>entry.registryId)).size>1) return {ok:false,reason:"ambiguous",candidates}; if (target.registryId === undefined && matches[0].registryId !== OFFICIAL_REGISTRY_ID) return {ok:false,reason:"qualification_required",candidates}; return {ok:true,entry:[...matches].sort((a,b)=>-(semverCompare(a.version,b.version) ?? 0))[0]}; }
export type InstallState = "available" | "installed" | "update";
export function installState(entry: Pick<QualifiedRegistryEntry,"version">, installedVersion?: string, installedSource?: "registry"|"local"|"development"): InstallState { if (!installedVersion) return "available"; if (installedSource !== "registry") return "installed"; return semverCompare(entry.version,installedVersion)===1 ? "update" : "installed"; }
export function isOfficial(entries: readonly QualifiedRegistryEntry[], id: string): boolean { return entries.some((entry)=>entry.registryId===OFFICIAL_REGISTRY_ID&&entry.id===id); }
export function catalogLabel(entry: Pick<QualifiedRegistryEntry,"id">): LocalizedText { return entry.id; }
