// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as Service from "./service.js";
export {
    Service
};

export {
    AppliedSurface,
    Frame,
    Receipt,
    Snapshot,
    Surface
} from "./models.js";

import * as $models from "./models.js";

/**
 * @typedef {$models.SurfaceKind} SurfaceKind
 */

/**
 * SurfaceSource is opaque to the compositor. The native surface plugin owns
 * the meaning of its declared keys.
 * @typedef {$models.SurfaceSource} SurfaceSource
 */
