// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AppliedSurface {
    "id": string;
    "generation": number;
    "frame": Frame;

    /**
     * Settled is the native view's raw layout frame when presentation differs from layout during
     * an interactive phase. Nil means this native kind has no separate settled geometry.
     */
    "settled"?: Frame | null;
    "layerContentsRedrawPolicy": number;
    "layerContentsPlacement": number;
    "visible": boolean;
    "alpha": number;
    "layer": number;

    /**
     * Misparented reports that the surface is in a different window from the
     * one that declared it. The compositor sets it; a backend's own value is
     * overwritten.
     * 
     * Every other number here is a fact about a rectangle inside some window,
     * so all of them read correct while the rectangle sits in a window nobody
     * is looking at. Measured 2026-08-16: declared and applied frames agreed to
     * zero drift, visible was true, alpha was 1, and the pane on screen was
     * empty.
     */
    "misparented": boolean;

    /** Creates a new AppliedSurface instance. */
    constructor($$source: Partial<AppliedSurface> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("generation" in $$source)) {
            this["generation"] = 0;
        }
        if (!("frame" in $$source)) {
            this["frame"] = (new Frame());
        }
        if (!("layerContentsRedrawPolicy" in $$source)) {
            this["layerContentsRedrawPolicy"] = 0;
        }
        if (!("layerContentsPlacement" in $$source)) {
            this["layerContentsPlacement"] = 0;
        }
        if (!("visible" in $$source)) {
            this["visible"] = false;
        }
        if (!("alpha" in $$source)) {
            this["alpha"] = 0;
        }
        if (!("layer" in $$source)) {
            this["layer"] = 0;
        }
        if (!("misparented" in $$source)) {
            this["misparented"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppliedSurface instance from a string or object.
     */
    static createFrom($$source: any = {}): AppliedSurface {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("frame" in $$parsedSource) {
            $$parsedSource["frame"] = $$createField2_0($$parsedSource["frame"]);
        }
        if ("settled" in $$parsedSource) {
            $$parsedSource["settled"] = $$createField3_0($$parsedSource["settled"]);
        }
        return new AppliedSurface($$parsedSource as Partial<AppliedSurface>);
    }
}

/**
 * Composition is one window's last commit read as a comparison.
 */
export class Composition {
    /**
     * Sequence is the commit these numbers came from. Zero means no inventory
     * has ever been applied to this window, which is a different answer from an
     * inventory that was applied and held nothing: one is a compositor that has
     * never run, the other is a window whose document declares no surface.
     */
    "sequence": number;

    /**
     * AppliedAtUnixMs is when the backend finished applying this exact inventory.
     */
    "appliedAtUnixMs": number;

    /**
     * Interactive is the explicit layout phase carried by this commit.
     */
    "interactive": boolean;

    /**
     * Surfaces is one entry per surface either half holds.
     */
    "surfaces": Placement[];

    /**
     * Unapplied names the surfaces the document declared and the backend did
     * not report back. A count that agreed while the screen did not is what
     * this list prevents.
     */
    "unapplied": string[];

    /**
     * Failure names the most recent attempt that did not land.
     */
    "failure"?: string;

    /**
     * FailedSequence is the sequence of that attempt.
     */
    "failedSequence"?: number;

    /** Creates a new Composition instance. */
    constructor($$source: Partial<Composition> = {}) {
        if (!("sequence" in $$source)) {
            this["sequence"] = 0;
        }
        if (!("appliedAtUnixMs" in $$source)) {
            this["appliedAtUnixMs"] = 0;
        }
        if (!("interactive" in $$source)) {
            this["interactive"] = false;
        }
        if (!("surfaces" in $$source)) {
            this["surfaces"] = [];
        }
        if (!("unapplied" in $$source)) {
            this["unapplied"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Composition instance from a string or object.
     */
    static createFrom($$source: any = {}): Composition {
        const $$createField3_0 = $$createType3;
        const $$createField4_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("surfaces" in $$parsedSource) {
            $$parsedSource["surfaces"] = $$createField3_0($$parsedSource["surfaces"]);
        }
        if ("unapplied" in $$parsedSource) {
            $$parsedSource["unapplied"] = $$createField4_0($$parsedSource["unapplied"]);
        }
        return new Composition($$parsedSource as Partial<Composition>);
    }
}

/**
 * Cover is what lies over one surface.
 */
export class Cover {
    /**
     * By names the surfaces found over this one, in no order. Empty means every point sampled
     * inside it belongs to it.
     */
    "by": string[];

    /**
     * Fraction is how much of it they hold, 0 through 1, sampled. Exactly 1 is every sampled point
     * belonging to something else, which is a surface nobody can see any of.
     */
    "fraction": number;

    /** Creates a new Cover instance. */
    constructor($$source: Partial<Cover> = {}) {
        if (!("by" in $$source)) {
            this["by"] = [];
        }
        if (!("fraction" in $$source)) {
            this["fraction"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Cover instance from a string or object.
     */
    static createFrom($$source: any = {}): Cover {
        const $$createField0_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("by" in $$parsedSource) {
            $$parsedSource["by"] = $$createField0_0($$parsedSource["by"]);
        }
        return new Cover($$parsedSource as Partial<Cover>);
    }
}

export class Frame {
    "x": number;
    "y": number;
    "width": number;
    "height": number;

    /** Creates a new Frame instance. */
    constructor($$source: Partial<Frame> = {}) {
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Frame instance from a string or object.
     */
    static createFrom($$source: any = {}): Frame {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Frame($$parsedSource as Partial<Frame>);
    }
}

/**
 * Placement is one surface at one commit: both halves and their difference,
 * read in the same instant.
 * 
 * Same instant is the point. Read from two places at two moments, a live resize
 * turns a correct layer into a drift report and back again depending on which
 * read won.
 */
export class Placement {
    "id": string;
    "kind": SurfaceKind;
    "generation": number;
    "layer": number;
    "declared": Frame;
    "declaredVisible": boolean;
    "declaredAlpha": number;
    "applied": Frame;
    "settled"?: Frame | null;
    "layerContentsRedrawPolicy": number;
    "layerContentsPlacement": number;
    "appliedVisible": boolean;
    "appliedAlpha": number;

    /**
     * Drift is the applied rectangle minus the declared one, per component.
     * 
     * Exact, with no tolerance. Both halves are the same float64 travelling one
     * commit, so zero is reachable; a tolerance chosen without a measurement
     * hides the first hundredth of a point of the next coordinate error. A
     * caller that wants to forgive a rounding difference has the number.
     * 
     * Nil on an undeclared surface, rather than zero. Zero is the answer for a
     * surface applied exactly where it was declared, and a surface no
     * declaration asked for is the opposite of that. There is no second
     * rectangle to subtract.
     */
    "drift": Frame | null;

    /**
     * Misparented reports that the surface is in a different window from the
     * one whose document declared it, read off the native object rather than
     * restated from the declaration. Not a difference — a window is not a
     * distance — so it stays out of Drift.
     */
    "misparented": boolean;

    /**
     * Undeclared marks a surface the native layer holds that no declaration
     * asked for. It is the defect a ledger-only check cannot find: an
     * application walks its own records, so a surface that left the records and
     * stayed on screen is invisible to every check the application makes.
     */
    "undeclared": boolean;

    /** Creates a new Placement instance. */
    constructor($$source: Partial<Placement> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("generation" in $$source)) {
            this["generation"] = 0;
        }
        if (!("layer" in $$source)) {
            this["layer"] = 0;
        }
        if (!("declared" in $$source)) {
            this["declared"] = (new Frame());
        }
        if (!("declaredVisible" in $$source)) {
            this["declaredVisible"] = false;
        }
        if (!("declaredAlpha" in $$source)) {
            this["declaredAlpha"] = 0;
        }
        if (!("applied" in $$source)) {
            this["applied"] = (new Frame());
        }
        if (!("layerContentsRedrawPolicy" in $$source)) {
            this["layerContentsRedrawPolicy"] = 0;
        }
        if (!("layerContentsPlacement" in $$source)) {
            this["layerContentsPlacement"] = 0;
        }
        if (!("appliedVisible" in $$source)) {
            this["appliedVisible"] = false;
        }
        if (!("appliedAlpha" in $$source)) {
            this["appliedAlpha"] = 0;
        }
        if (!("drift" in $$source)) {
            this["drift"] = null;
        }
        if (!("misparented" in $$source)) {
            this["misparented"] = false;
        }
        if (!("undeclared" in $$source)) {
            this["undeclared"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Placement instance from a string or object.
     */
    static createFrom($$source: any = {}): Placement {
        const $$createField4_0 = $$createType0;
        const $$createField7_0 = $$createType0;
        const $$createField8_0 = $$createType1;
        const $$createField13_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("declared" in $$parsedSource) {
            $$parsedSource["declared"] = $$createField4_0($$parsedSource["declared"]);
        }
        if ("applied" in $$parsedSource) {
            $$parsedSource["applied"] = $$createField7_0($$parsedSource["applied"]);
        }
        if ("settled" in $$parsedSource) {
            $$parsedSource["settled"] = $$createField8_0($$parsedSource["settled"]);
        }
        if ("drift" in $$parsedSource) {
            $$parsedSource["drift"] = $$createField13_0($$parsedSource["drift"]);
        }
        return new Placement($$parsedSource as Partial<Placement>);
    }
}

export class Receipt {
    "sequence": number;
    "accepted": boolean;
    "surfaces": AppliedSurface[];

    /**
     * AppliedAtUnixMs is the wall-clock instant immediately after the backend applied this inventory.
     * It is recorded here, where Apply actually returns. A frontend response timestamp includes the
     * return bridge and cannot say when the native view moved.
     */
    "appliedAtUnixMs": number;

    /**
     * AppliedMs is how long the backend held this commit — the native work alone, without the
     * bridge that carried the request or the wait for a thread that was busy with something else.
     * 
     * A caller measuring a commit from the other side of the bridge measures both, and the two ask
     * different questions: work the application does costs this, and time it spends waiting is the
     * window being busy elsewhere. Measured 2026-08-17, a window stopped drawing for exactly as long
     * as its commits took, and nothing could tell those two apart.
     */
    "appliedMs": number;

    /**
     * CarriedMs is how long the commit took to reach the backend from the document that sent
     * it — the bridge, the queue behind it, and whatever the main thread was doing instead.
     * 
     * -1 when the caller stamped nothing. A caller that stamps gets the round trip split in
     * two: this, and AppliedMs. What is left over is the answer's way back.
     */
    "carriedMs": number;

    /** Creates a new Receipt instance. */
    constructor($$source: Partial<Receipt> = {}) {
        if (!("sequence" in $$source)) {
            this["sequence"] = 0;
        }
        if (!("accepted" in $$source)) {
            this["accepted"] = false;
        }
        if (!("surfaces" in $$source)) {
            this["surfaces"] = [];
        }
        if (!("appliedAtUnixMs" in $$source)) {
            this["appliedAtUnixMs"] = 0;
        }
        if (!("appliedMs" in $$source)) {
            this["appliedMs"] = 0;
        }
        if (!("carriedMs" in $$source)) {
            this["carriedMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Receipt instance from a string or object.
     */
    static createFrom($$source: any = {}): Receipt {
        const $$createField2_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("surfaces" in $$parsedSource) {
            $$parsedSource["surfaces"] = $$createField2_0($$parsedSource["surfaces"]);
        }
        return new Receipt($$parsedSource as Partial<Receipt>);
    }
}

export class Snapshot {
    /**
     * Window names the window whose document declared these surfaces.
     * 
     * A surface is attached to one window's content view and its frame is in that document's
     * coordinates. Without the name a host with two windows attaches every surface to whichever
     * one it happened to hand over, and the frames are read against the wrong box.
     */
    "window": string;
    "sequence": number;

    /**
     * Interactive is the layout system's explicit gesture phase. It is carried with the whole
     * inventory so each native kind owns how its live surface is presented during that phase.
     */
    "interactive": boolean;
    "surfaces": Surface[];

    /**
     * SentAtUnixMs is when the document handed this over, by its own wall clock.
     * 
     * A receipt says how long the backend held the commit and a caller measures the whole
     * round trip, and the difference between those two is time nobody could name. Measured
     * 2026-08-17 in a window changing its layout: 40ms round trip, 0.2ms of native work, and
     * no reading that said where the other 39.8 went. Stamped here, the crossing can be
     * subtracted from the round trip and what is left is the bridge.
     * 
     * Zero is a caller that does not stamp, and the receipt then reports no crossing rather
     * than a number made from two clocks that never met.
     */
    "sentAtUnixMs": number;

    /** Creates a new Snapshot instance. */
    constructor($$source: Partial<Snapshot> = {}) {
        if (!("window" in $$source)) {
            this["window"] = "";
        }
        if (!("sequence" in $$source)) {
            this["sequence"] = 0;
        }
        if (!("interactive" in $$source)) {
            this["interactive"] = false;
        }
        if (!("surfaces" in $$source)) {
            this["surfaces"] = [];
        }
        if (!("sentAtUnixMs" in $$source)) {
            this["sentAtUnixMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Snapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): Snapshot {
        const $$createField3_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("surfaces" in $$parsedSource) {
            $$parsedSource["surfaces"] = $$createField3_0($$parsedSource["surfaces"]);
        }
        return new Snapshot($$parsedSource as Partial<Snapshot>);
    }
}

export class Surface {
    "id": string;
    "generation": number;
    "kind": SurfaceKind;
    "frame": Frame;
    "visible": boolean;
    "alpha": number;
    "layer": number;
    "source": SurfaceSource;

    /** Creates a new Surface instance. */
    constructor($$source: Partial<Surface> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("generation" in $$source)) {
            this["generation"] = 0;
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("frame" in $$source)) {
            this["frame"] = (new Frame());
        }
        if (!("visible" in $$source)) {
            this["visible"] = false;
        }
        if (!("alpha" in $$source)) {
            this["alpha"] = 0;
        }
        if (!("layer" in $$source)) {
            this["layer"] = 0;
        }
        if (!("source" in $$source)) {
            this["source"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Surface instance from a string or object.
     */
    static createFrom($$source: any = {}): Surface {
        const $$createField3_0 = $$createType0;
        const $$createField7_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("frame" in $$parsedSource) {
            $$parsedSource["frame"] = $$createField3_0($$parsedSource["frame"]);
        }
        if ("source" in $$parsedSource) {
            $$parsedSource["source"] = $$createField7_0($$parsedSource["source"]);
        }
        return new Surface($$parsedSource as Partial<Surface>);
    }
}

export type SurfaceKind = string;

/**
 * SurfaceSource is opaque to the compositor. The native surface plugin owns
 * the meaning of its declared keys.
 */
export type SurfaceSource = { [_ in string]?: string };

// Private type creation functions
const $$createType0 = Frame.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = Placement.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = AppliedSurface.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = Surface.createFrom;
const $$createType8 = $Create.Array($$createType7);
var $$createType9 = (function $$initCreateType9(...args: any[]): any {
    if ($$createType9 === $$initCreateType9) {
        $$createType9 = $$createType10;
    }
    return $$createType9(...args);
});
const $$createType10 = $Create.Map($Create.Any, $Create.Any);
