// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AppliedSurface {
    "id": string;
    "generation": number;
    "frame": Frame;
    "visible": boolean;
    "alpha": number;
    "layer": number;

    /** Creates a new AppliedSurface instance. */
    constructor($$source: Partial<AppliedSurface> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("generation" in $$source)) {
            this["generation"] = 0;
        }
        if (!("frame" in $$source)) {
            this["frame"] = (new Frame());
        }
        if (!("visible" in $$source)) {
            this["visible"] = false;
        }
        if (!("alpha" in $$source)) {
            this["alpha"] = 0;
        }
        if (!("layer" in $$source)) {
            this["layer"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppliedSurface instance from a string or object.
     */
    static createFrom($$source: any = {}): AppliedSurface {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("frame" in $$parsedSource) {
            $$parsedSource["frame"] = $$createField2_0($$parsedSource["frame"]);
        }
        return new AppliedSurface($$parsedSource as Partial<AppliedSurface>);
    }
}

/**
 * Declared is the inventory the document asked for on the last accepted commit,
 * and Applied is what the native layer reported back.
 * 
 * Both halves come from one commit. A consumer that measured drift against the
 * applied half alone would compare a value with itself and read zero every
 * time; a consumer that read the declared half from the document would be
 * reading a later frame than the one that was applied.
 */
export class Committed {
    "declared": Snapshot;
    "applied": Receipt;

    /**
     * Failure is the backend's reason for the most recent attempt that did not
     * land, empty when the last attempt landed. Without it a backend that
     * refuses every new inventory keeps answering with the last healthy one,
     * and every reading reports a healthy layer.
     */
    "failure": string;

    /**
     * FailedSequence is the sequence of that attempt.
     */
    "failedSequence": number;

    /** Creates a new Committed instance. */
    constructor($$source: Partial<Committed> = {}) {
        if (!("declared" in $$source)) {
            this["declared"] = (new Snapshot());
        }
        if (!("applied" in $$source)) {
            this["applied"] = (new Receipt());
        }
        if (!("failure" in $$source)) {
            this["failure"] = "";
        }
        if (!("failedSequence" in $$source)) {
            this["failedSequence"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Committed instance from a string or object.
     */
    static createFrom($$source: any = {}): Committed {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("declared" in $$parsedSource) {
            $$parsedSource["declared"] = $$createField0_0($$parsedSource["declared"]);
        }
        if ("applied" in $$parsedSource) {
            $$parsedSource["applied"] = $$createField1_0($$parsedSource["applied"]);
        }
        return new Committed($$parsedSource as Partial<Committed>);
    }
}

export class Frame {
    "x": number;
    "y": number;
    "width": number;
    "height": number;

    /** Creates a new Frame instance. */
    constructor($$source: Partial<Frame> = {}) {
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Frame instance from a string or object.
     */
    static createFrom($$source: any = {}): Frame {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Frame($$parsedSource as Partial<Frame>);
    }
}

export class Receipt {
    "sequence": number;
    "accepted": boolean;
    "surfaces": AppliedSurface[];

    /** Creates a new Receipt instance. */
    constructor($$source: Partial<Receipt> = {}) {
        if (!("sequence" in $$source)) {
            this["sequence"] = 0;
        }
        if (!("accepted" in $$source)) {
            this["accepted"] = false;
        }
        if (!("surfaces" in $$source)) {
            this["surfaces"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Receipt instance from a string or object.
     */
    static createFrom($$source: any = {}): Receipt {
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("surfaces" in $$parsedSource) {
            $$parsedSource["surfaces"] = $$createField2_0($$parsedSource["surfaces"]);
        }
        return new Receipt($$parsedSource as Partial<Receipt>);
    }
}

export class Snapshot {
    /**
     * Window names the window whose document declared these surfaces.
     * 
     * A surface is attached to one window's content view and its frame is in that document's
     * coordinates. Without the name a host with two windows attaches every surface to whichever
     * one it happened to hand over, and the frames are read against the wrong box.
     */
    "window": string;
    "sequence": number;
    "surfaces": Surface[];

    /** Creates a new Snapshot instance. */
    constructor($$source: Partial<Snapshot> = {}) {
        if (!("window" in $$source)) {
            this["window"] = "";
        }
        if (!("sequence" in $$source)) {
            this["sequence"] = 0;
        }
        if (!("surfaces" in $$source)) {
            this["surfaces"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Snapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): Snapshot {
        const $$createField2_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("surfaces" in $$parsedSource) {
            $$parsedSource["surfaces"] = $$createField2_0($$parsedSource["surfaces"]);
        }
        return new Snapshot($$parsedSource as Partial<Snapshot>);
    }
}

export class Surface {
    "id": string;
    "generation": number;
    "kind": SurfaceKind;
    "frame": Frame;
    "visible": boolean;
    "alpha": number;
    "layer": number;
    "source": SurfaceSource;

    /** Creates a new Surface instance. */
    constructor($$source: Partial<Surface> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("generation" in $$source)) {
            this["generation"] = 0;
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("frame" in $$source)) {
            this["frame"] = (new Frame());
        }
        if (!("visible" in $$source)) {
            this["visible"] = false;
        }
        if (!("alpha" in $$source)) {
            this["alpha"] = 0;
        }
        if (!("layer" in $$source)) {
            this["layer"] = 0;
        }
        if (!("source" in $$source)) {
            this["source"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Surface instance from a string or object.
     */
    static createFrom($$source: any = {}): Surface {
        const $$createField3_0 = $$createType0;
        const $$createField7_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("frame" in $$parsedSource) {
            $$parsedSource["frame"] = $$createField3_0($$parsedSource["frame"]);
        }
        if ("source" in $$parsedSource) {
            $$parsedSource["source"] = $$createField7_0($$parsedSource["source"]);
        }
        return new Surface($$parsedSource as Partial<Surface>);
    }
}

export type SurfaceKind = string;

/**
 * SurfaceSource is opaque to the compositor. The native surface plugin owns
 * the meaning of its declared keys.
 */
export type SurfaceSource = { [_ in string]?: string };

// Private type creation functions
const $$createType0 = Frame.createFrom;
const $$createType1 = Snapshot.createFrom;
const $$createType2 = Receipt.createFrom;
const $$createType3 = AppliedSurface.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = Surface.createFrom;
const $$createType6 = $Create.Array($$createType5);
var $$createType7 = (function $$initCreateType7(...args: any[]): any {
    if ($$createType7 === $$initCreateType7) {
        $$createType7 = $$createType8;
    }
    return $$createType7(...args);
});
const $$createType8 = $Create.Map($Create.Any, $Create.Any);
