// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AppliedSurface {
    /**
     * Creates a new AppliedSurface instance.
     * @param {Partial<AppliedSurface>} [$$source = {}] - The source object to create the AppliedSurface.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("generation" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["generation"] = 0;
        }
        if (!("frame" in $$source)) {
            /**
             * @member
             * @type {Frame}
             */
            this["frame"] = (new Frame());
        }
        if (!("visible" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["visible"] = false;
        }
        if (!("alpha" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["alpha"] = 0;
        }
        if (!("layer" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["layer"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppliedSurface instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppliedSurface}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("frame" in $$parsedSource) {
            $$parsedSource["frame"] = $$createField2_0($$parsedSource["frame"]);
        }
        return new AppliedSurface(/** @type {Partial<AppliedSurface>} */($$parsedSource));
    }
}

export class Frame {
    /**
     * Creates a new Frame instance.
     * @param {Partial<Frame>} [$$source = {}] - The source object to create the Frame.
     */
    constructor($$source = {}) {
        if (!("x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["y"] = 0;
        }
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Frame instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Frame}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Frame(/** @type {Partial<Frame>} */($$parsedSource));
    }
}

export class Receipt {
    /**
     * Creates a new Receipt instance.
     * @param {Partial<Receipt>} [$$source = {}] - The source object to create the Receipt.
     */
    constructor($$source = {}) {
        if (!("sequence" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sequence"] = 0;
        }
        if (!("accepted" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["accepted"] = false;
        }
        if (!("surfaces" in $$source)) {
            /**
             * @member
             * @type {AppliedSurface[]}
             */
            this["surfaces"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Receipt instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Receipt}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("surfaces" in $$parsedSource) {
            $$parsedSource["surfaces"] = $$createField2_0($$parsedSource["surfaces"]);
        }
        return new Receipt(/** @type {Partial<Receipt>} */($$parsedSource));
    }
}

export class Snapshot {
    /**
     * Creates a new Snapshot instance.
     * @param {Partial<Snapshot>} [$$source = {}] - The source object to create the Snapshot.
     */
    constructor($$source = {}) {
        if (!("sequence" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sequence"] = 0;
        }
        if (!("surfaces" in $$source)) {
            /**
             * @member
             * @type {Surface[]}
             */
            this["surfaces"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Snapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Snapshot}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("surfaces" in $$parsedSource) {
            $$parsedSource["surfaces"] = $$createField1_0($$parsedSource["surfaces"]);
        }
        return new Snapshot(/** @type {Partial<Snapshot>} */($$parsedSource));
    }
}

export class Surface {
    /**
     * Creates a new Surface instance.
     * @param {Partial<Surface>} [$$source = {}] - The source object to create the Surface.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("generation" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["generation"] = 0;
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {SurfaceKind}
             */
            this["kind"] = "";
        }
        if (!("frame" in $$source)) {
            /**
             * @member
             * @type {Frame}
             */
            this["frame"] = (new Frame());
        }
        if (!("visible" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["visible"] = false;
        }
        if (!("alpha" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["alpha"] = 0;
        }
        if (!("layer" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["layer"] = 0;
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {SurfaceSource}
             */
            this["source"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Surface instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Surface}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        const $$createField7_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("frame" in $$parsedSource) {
            $$parsedSource["frame"] = $$createField3_0($$parsedSource["frame"]);
        }
        if ("source" in $$parsedSource) {
            $$parsedSource["source"] = $$createField7_0($$parsedSource["source"]);
        }
        return new Surface(/** @type {Partial<Surface>} */($$parsedSource));
    }
}

/**
 * @typedef {string} SurfaceKind
 */

/**
 * SurfaceSource is opaque to the compositor. The native surface plugin owns
 * the meaning of its declared keys.
 * @typedef {{ [_ in string]?: string }} SurfaceSource
 */

// Private type creation functions
const $$createType0 = Frame.createFrom;
const $$createType1 = AppliedSurface.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = Surface.createFrom;
const $$createType4 = $Create.Array($$createType3);
var $$createType5 = /** @type {(...args: any[]) => any} */(function $$initCreateType5(...args) {
    if ($$createType5 === $$initCreateType5) {
        $$createType5 = $$createType6;
    }
    return $$createType5(...args);
});
const $$createType6 = $Create.Map($Create.Any, $Create.Any);
