// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AppliedSurface {
    "id": string;
    "generation": number;
    "frame": Frame;
    "visible": boolean;
    "alpha": number;
    "layer": number;

    /** Creates a new AppliedSurface instance. */
    constructor($$source: Partial<AppliedSurface> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("generation" in $$source)) {
            this["generation"] = 0;
        }
        if (!("frame" in $$source)) {
            this["frame"] = (new Frame());
        }
        if (!("visible" in $$source)) {
            this["visible"] = false;
        }
        if (!("alpha" in $$source)) {
            this["alpha"] = 0;
        }
        if (!("layer" in $$source)) {
            this["layer"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppliedSurface instance from a string or object.
     */
    static createFrom($$source: any = {}): AppliedSurface {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("frame" in $$parsedSource) {
            $$parsedSource["frame"] = $$createField2_0($$parsedSource["frame"]);
        }
        return new AppliedSurface($$parsedSource as Partial<AppliedSurface>);
    }
}

export class Frame {
    "x": number;
    "y": number;
    "width": number;
    "height": number;

    /** Creates a new Frame instance. */
    constructor($$source: Partial<Frame> = {}) {
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Frame instance from a string or object.
     */
    static createFrom($$source: any = {}): Frame {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Frame($$parsedSource as Partial<Frame>);
    }
}

export class Receipt {
    "sequence": number;
    "accepted": boolean;
    "surfaces": AppliedSurface[];

    /** Creates a new Receipt instance. */
    constructor($$source: Partial<Receipt> = {}) {
        if (!("sequence" in $$source)) {
            this["sequence"] = 0;
        }
        if (!("accepted" in $$source)) {
            this["accepted"] = false;
        }
        if (!("surfaces" in $$source)) {
            this["surfaces"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Receipt instance from a string or object.
     */
    static createFrom($$source: any = {}): Receipt {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("surfaces" in $$parsedSource) {
            $$parsedSource["surfaces"] = $$createField2_0($$parsedSource["surfaces"]);
        }
        return new Receipt($$parsedSource as Partial<Receipt>);
    }
}

export class Snapshot {
    "sequence": number;
    "surfaces": Surface[];

    /** Creates a new Snapshot instance. */
    constructor($$source: Partial<Snapshot> = {}) {
        if (!("sequence" in $$source)) {
            this["sequence"] = 0;
        }
        if (!("surfaces" in $$source)) {
            this["surfaces"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Snapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): Snapshot {
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("surfaces" in $$parsedSource) {
            $$parsedSource["surfaces"] = $$createField1_0($$parsedSource["surfaces"]);
        }
        return new Snapshot($$parsedSource as Partial<Snapshot>);
    }
}

export class Surface {
    "id": string;
    "generation": number;
    "kind": SurfaceKind;
    "frame": Frame;
    "visible": boolean;
    "alpha": number;
    "layer": number;
    "source": SurfaceSource;

    /** Creates a new Surface instance. */
    constructor($$source: Partial<Surface> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("generation" in $$source)) {
            this["generation"] = 0;
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("frame" in $$source)) {
            this["frame"] = (new Frame());
        }
        if (!("visible" in $$source)) {
            this["visible"] = false;
        }
        if (!("alpha" in $$source)) {
            this["alpha"] = 0;
        }
        if (!("layer" in $$source)) {
            this["layer"] = 0;
        }
        if (!("source" in $$source)) {
            this["source"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Surface instance from a string or object.
     */
    static createFrom($$source: any = {}): Surface {
        const $$createField3_0 = $$createType0;
        const $$createField7_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("frame" in $$parsedSource) {
            $$parsedSource["frame"] = $$createField3_0($$parsedSource["frame"]);
        }
        if ("source" in $$parsedSource) {
            $$parsedSource["source"] = $$createField7_0($$parsedSource["source"]);
        }
        return new Surface($$parsedSource as Partial<Surface>);
    }
}

export type SurfaceKind = string;

/**
 * SurfaceSource is opaque to the compositor. The native surface plugin owns
 * the meaning of its declared keys.
 */
export type SurfaceSource = { [_ in string]?: string };

// Private type creation functions
const $$createType0 = Frame.createFrom;
const $$createType1 = AppliedSurface.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = Surface.createFrom;
const $$createType4 = $Create.Array($$createType3);
var $$createType5 = (function $$initCreateType5(...args: any[]): any {
    if ($$createType5 === $$initCreateType5) {
        $$createType5 = $$createType6;
    }
    return $$createType5(...args);
});
const $$createType6 = $Create.Map($Create.Any, $Create.Any);
