// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service places declared surfaces in the windows that declared them.
 * 
 * State is per window, all of it. One window's sequence counter, inventory and
 * last commit say nothing about another's: a shared counter answers the second
 * window's first commit as stale behind the first window's tenth, and a shared
 * inventory answers a question about one window with every window's surfaces.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Commit(snapshot: $models.Snapshot): $CancellablePromise<$models.Receipt> {
    return $Call.ByID(2753490429, snapshot).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Deliver forwards a message to the backend that owns a surface.
 * 
 * The inventory is the only record of what exists, so a message for an id nobody declared is
 * refused here. Forwarding it would ask the backend to invent a surface, and a backend that obliges
 * holds one the compositor does not know about — the undeclared surface a ledger-only check never
 * sees, because the ledger is what it walks.
 */
export function Deliver(id: string, message: { [_ in string]?: any }): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(1390608961, id, message).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Latest answers both halves of one window's last commit.
 */
export function Latest(window: string): $CancellablePromise<$models.Committed> {
    return $Call.ByID(2745712171, window).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Status answers one window's applied inventory.
 */
export function Status(window: string): $CancellablePromise<$models.Receipt> {
    return $Call.ByID(2286254498, window).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Windows names every window this service has accepted a commit for, sorted.
 * 
 * A reader that has to know the window names in advance cannot sweep, and a
 * surface in a window nobody thought to ask about is the one that goes missing.
 */
export function Windows(): $CancellablePromise<string[]> {
    return $Call.ByID(3374928189).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = $models.Receipt.createFrom;
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = $models.Committed.createFrom;
const $$createType3 = $Create.Array($Create.Any);
