// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Navigate(id: string, generation: number, url: string): $CancellablePromise<void> {
    return $Call.ByID(949452520, id, generation, url);
}

export function Status(): $CancellablePromise<$models.SurfaceStatus[]> {
    return $Call.ByID(1138459829).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.SurfaceStatus.createFrom;
const $$createType1 = $Create.Array($$createType0);
