// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Frame {
    /**
     * Creates a new Frame instance.
     * @param {Partial<Frame>} [$$source = {}] - The source object to create the Frame.
     */
    constructor($$source = {}) {
        if (!("x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["y"] = 0;
        }
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Frame instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Frame}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Frame(/** @type {Partial<Frame>} */($$parsedSource));
    }
}

export class Handle {
    /**
     * Creates a new Handle instance.
     * @param {Partial<Handle>} [$$source = {}] - The source object to create the Handle.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("generation" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["generation"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Handle instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Handle}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Handle(/** @type {Partial<Handle>} */($$parsedSource));
    }
}

export class Receipt {
    /**
     * Creates a new Receipt instance.
     * @param {Partial<Receipt>} [$$source = {}] - The source object to create the Receipt.
     */
    constructor($$source = {}) {
        if (!("handle" in $$source)) {
            /**
             * @member
             * @type {Handle}
             */
            this["handle"] = (new Handle());
        }
        if (!("sequence" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sequence"] = 0;
        }
        if (!("accepted" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["accepted"] = false;
        }
        if (!("requested" in $$source)) {
            /**
             * @member
             * @type {Frame}
             */
            this["requested"] = (new Frame());
        }
        if (!("applied" in $$source)) {
            /**
             * @member
             * @type {Frame}
             */
            this["applied"] = (new Frame());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Receipt instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Receipt}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("handle" in $$parsedSource) {
            $$parsedSource["handle"] = $$createField0_0($$parsedSource["handle"]);
        }
        if ("requested" in $$parsedSource) {
            $$parsedSource["requested"] = $$createField3_0($$parsedSource["requested"]);
        }
        if ("applied" in $$parsedSource) {
            $$parsedSource["applied"] = $$createField4_0($$parsedSource["applied"]);
        }
        return new Receipt(/** @type {Partial<Receipt>} */($$parsedSource));
    }
}

export const SurfaceStatus = Receipt;

/**
 * @typedef {Receipt} SurfaceStatus
 */

// Private type creation functions
const $$createType0 = Handle.createFrom;
const $$createType1 = Frame.createFrom;
