// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {$models.Handle} handle
 * @returns {$CancellablePromise<void>}
 */
export function Close(handle) {
    return $Call.ByID(269751632, handle);
}

/**
 * @param {$models.Handle} handle
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function Navigate(handle, url) {
    return $Call.ByID(1729946423, handle, url);
}

/**
 * @param {string} id
 * @param {string} url
 * @param {number} sequence
 * @param {$models.Frame} frame
 * @returns {$CancellablePromise<$models.Receipt>}
 */
export function Open(id, url, sequence, frame) {
    return $Call.ByID(3504042700, id, url, sequence, frame).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.Handle} handle
 * @param {number} sequence
 * @param {$models.Frame} frame
 * @returns {$CancellablePromise<$models.Receipt>}
 */
export function SetFrame(handle, sequence, frame) {
    return $Call.ByID(3022238273, handle, sequence, frame).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.SurfaceStatus[]>}
 */
export function Status() {
    return $Call.ByID(3840696598).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.Receipt.createFrom;
const $$createType1 = $Create.Array($$createType0);
