// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Owner names who answers a command, and it travels in the greeting.
 * 
 * It is on the wire because a client reads it: a command owned by the framework needs this host's
 * window and cannot be answered headless, and a caller that could not tell which is which would ask
 * a window-less process for a window's answer and read the refusal as a missing feature.
 */
export enum Owner {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    OwnerCore = "core",
    OwnerFramework = "framework",
    OwnerPlugin = "plugin",
};

/**
 * Served describes a command the answering side answers.
 */
export class Served {
    "name": string;
    "owner": Owner;

    /** Creates a new Served instance. */
    constructor($$source: Partial<Served> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("owner" in $$source)) {
            this["owner"] = Owner.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Served instance from a string or object.
     */
    static createFrom($$source: any = {}): Served {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Served($$parsedSource as Partial<Served>);
    }
}

/**
 * Table is what the answering side serves and what it refuses, together.
 */
export class Table {
    "commands": Served[];
    "unserved": Unserved[];

    /** Creates a new Table instance. */
    constructor($$source: Partial<Table> = {}) {
        if (!("commands" in $$source)) {
            this["commands"] = [];
        }
        if (!("unserved" in $$source)) {
            this["unserved"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Table instance from a string or object.
     */
    static createFrom($$source: any = {}): Table {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("commands" in $$parsedSource) {
            $$parsedSource["commands"] = $$createField0_0($$parsedSource["commands"]);
        }
        if ("unserved" in $$parsedSource) {
            $$parsedSource["unserved"] = $$createField1_0($$parsedSource["unserved"]);
        }
        return new Table($$parsedSource as Partial<Table>);
    }
}

/**
 * Unserved describes a command the answering side refuses, and why.
 */
export class Unserved {
    "name": string;

    /**
     * BlockedBy separates "not written yet" from "impossible here". A caller that receives only
     * "unknown command" re-investigates settled ground, or imitates the command.
     */
    "blockedBy": string;

    /** Creates a new Unserved instance. */
    constructor($$source: Partial<Unserved> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("blockedBy" in $$source)) {
            this["blockedBy"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Unserved instance from a string or object.
     */
    static createFrom($$source: any = {}): Unserved {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Unserved($$parsedSource as Partial<Unserved>);
    }
}

// Private type creation functions
const $$createType0 = Served.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = Unserved.createFrom;
const $$createType3 = $Create.Array($$createType2);
